server:
  port: 7001
spring:
  application:
    name: eurekaserve-7001
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/