server:
  port: 7002
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eurekaserver7002 #host文件配置映射
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
       defaultZone: http://eurekaserver7001:7001/eureka/
  server:
    enable-self-preservation: false #关闭自我保护模式
    eviction-interval-timer-in-ms: 4000 #清理服务间隔4s，默认60*10000