server:
  port: 7001
spring:
  application:
    name: eurekaserver-7001
eureka:
  instance:
    hostname: eurekaserver7001 #host文件配置映射
  client:
    fetch-registry: false #是否将自己注册到Eureka Server 默认为true
    register-with-eureka: true  #是否从Eureka Server查询注册信息
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
       defaultZone: http://eurekaserver7002:7002/eureka/
  server:
    enable-self-preservation: false #关闭自我保护模式
    eviction-interval-timer-in-ms: 4000 #清理服务间隔4s，默认60*10000