server:
  port: 9001
spring:
  application:
    name: paymentserver
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/sskdb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: ssk
    password: 1415926ssk
eureka:
  instance:
    hostname: localhost
  client:
#    fetch-registry: false
#    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
# 安全认证的配置
security:
  basic:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ssk.**.mapper.**

#showSql
logging:
  level:
    com:
      example:
        mapper : debug