server:
  port: 7002
spring:
  application:
    name: eureka-server7002
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
       defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/